[project]
name = "gpu-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "crypto>=1.4.1",
    "numba>=0.62.1",
    "numpy>=2.2.6",
    "pycryptodome>=3.23.0",
]
